version: '3.6'
services:
  postgres-compose:
    container_name: postgres-compose
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass
    ports:
      - "15432:5432"
    volumes:
      - /PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-compose:
    container_name: pgadmin-compose
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pass"
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge