server:
  port: 8082
  servlet:
    context-path: /userMicroService
    
spring:
  application:
    name: userMicroService
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/ms_user
    username: root
    password: pass
    
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

user:
  rabbitmq:
    exchange: user.exchange
    routingkey: user.email.routingkey
    
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka
 