server:
  port: 8081
  servlet:
    context-path: /userMicroService
    
spring:
  application:
    name: userMicroService
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/ms_user
    username: root
    password: pass
