server:
  port: 8082
  servlet:
    context-path: /userMicroService
    
spring:
  application:
    name: userMicroService
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/ms_user
    username: root
    password: pass
    
  rabbitmq:
    addresses: amqps://bjwigwxc:hZatilqNom_Wjg37ymTOlHdD3m3o8r30@beaver.rmq.cloudamqp.com/bjwigwxc
    exchange: amq.direct
    routingkey: mail.routingkey
 
