server:
  port: 8083
  servlet:
    context-path: /mailMicroService
    
spring:
  application:
    name: mailMicroService
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/ms_email
    username: root
    password: pass
    
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: pedrobvferreira@gmail.com
    password: vhpfcoqrswbuvsdf
    properties:
      mail:
        auth: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
        starttls:
          enable:true
          
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    
user:
  rabbitmq:
    exchange: user.exchange
    queue: user.email.queue
      
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka
