server:
  port: 8083
  servlet:
    context-path: /mailMicroService
    
spring:
  application:
    name: mailMicroService
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/ms_email
    username: root
    password: pass
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: pedrobvferreira@gmail.com
    password: lgwoljbgrhlqcbsn
    properties:
      mail:
        auth: true
        starttls:
          enable:true
          
userMicroService:
  rabbitmq:
    exchange: userMicroService.exchange
    queue: userMicroService.user.queue
      