server:
  port: 8080
    
spring:
  application:
    name: gateway
    
eureka:
  instance: 
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka
      
zuul:
  prefix: /api
  ignored-services: "*"
  
  routes:
    mailMicroService:
      path: /mailMicroService/**
      service-id: mailMicroService
      strip-prefix: false
      custom-sensitive-headers: true
      
    userMicroService:
      path: /userMicroService/**
      service-id: userMicroService
      strip-prefix: false
      custom-sensitive-headers: true