version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.9.13-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret_pass
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
volumes:
  rabbitmq: